app/models/admin.py
from flask import flash, redirect, url_for
from flask_admin import AdminIndexView
from flask_admin.contrib.sqla import ModelView
from flask_login import current_user
from wtforms import BooleanField, Form, StringField
from wtforms.validators import DataRequired, Email


class AdminView(AdminIndexView):
    def is_accessible(self):
        return current_user.is_authenticated and current_user.is_admin

    def inaccessible_callback(self, name, **kwargs):
        flash('Você não tem permissão para acessar este recurso.', 'danger')
        return redirect(url_for('home_bp.index'))


class UserForm(Form):
    name = StringField('Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    is_admin = BooleanField('Is Admin')


class AdminUserView(ModelView):
    form = UserForm
    can_create = True
    column_list = ('id', 'name', 'email', 'is_admin')

app/models/book.py
from enum import Enum

from sqlalchemy import Enum as SQLEnum

from app.db import db


class BookStatus(Enum):
    new = 'new'
    used = 'used'
    semi_new = 'semi-new'


class Book(db.Model):
    __tablename__ = 'books'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(120), nullable=False)
    author = db.Column(db.String(120), nullable=False)
    genre = db.Column(db.String(120), nullable=False)
    publisher = db.Column(db.String(120))
    publication_date = db.Column(db.DateTime)
    status = db.Column(SQLEnum(BookStatus, name='book_status'), nullable=False)
    donated = db.Column(db.Boolean, nullable=False)
    unit_price = db.Column(db.Float, nullable=False)
    stock = db.Column(db.Integer, nullable=False)

app/models/user.py
from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash

from app.db import db


class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), nullable=False, unique=True)
    email = db.Column(db.String(120), unique=True, nullable=False)
    hashed_password = db.Column(db.String(128), nullable=False)
    is_admin = db.Column(db.Boolean, nullable=False, default=False)

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.hashed_password = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.hashed_password, password)

app/__init__.py
import flask_login
from flask import Flask
from flask_admin import Admin

from app.api.auth_controller import auth_controller_bp
from app.api.book_controller import book_controller_bp
from app.api.user_controller import user_controller_bp
from app.db import db, migrate
from app.error_handlers import register_error_handlers
from app.models import book as book
from app.models import user as user
from app.models.admin import AdminUserView, AdminView
from app.models.user import User
from app.routes.auth_routes import auth_bp
from app.routes.book_routes import book_bp
from app.routes.home_routes import home_bp
from app.routes.user_routes import user_bp
from config import Config

login_manager = flask_login.LoginManager()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    admin = Admin(app, name='agora_library',
                  template_mode='bootstrap3',
                  index_view=AdminView()
                  )
    admin.add_view(AdminUserView(User, db.session))
    register_error_handlers(app, login_manager)
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    login_manager.login_view = 'auth.login'

    app.register_blueprint(home_bp)
    app.register_blueprint(user_bp, url_prefix='/users')
    app.register_blueprint(auth_bp, url_prefix='/auth')
    app.register_blueprint(book_bp, url_prefix='/books')
    app.register_blueprint(auth_controller_bp,
                           url_prefix='/api/auth')
    app.register_blueprint(user_controller_bp,
                           url_prefix='/api/users')
    app.register_blueprint(book_controller_bp,
                           url_prefix='/api/books')

    return app

app/routes/auth_routes.py
from flask import Blueprint, render_template

auth_bp = Blueprint('auth_bp', __name__)


@auth_bp.route('/register', methods=['GET'])
def register():
    return render_template('auth/register.html', include_header=True)


@auth_bp.route('/login', methods=['GET'])
def login():
    return render_template('auth/login.html', include_header=True)

app/routes/book_routes.py
from flask import Blueprint, render_template

from app.services import book_service

book_bp = Blueprint('book_bp', __name__)


@book_bp.route('/catalog', methods=['GET'])
def catalog():
    books = book_service.get_all_books()
    return render_template('catalog.html', books=books, include_header=True)

@book_bp.route('', methods=['GET'])
def create_book():
    return render_template('book_creation_page.html', include_header=True)

app/routes/home_routes.py
from flask import Blueprint, render_template

home_bp = Blueprint('home_bp', __name__)


@home_bp.route('/')
def index():
    return render_template('home.html', include_header=True)

app/routes/user_routes.py
import flask_login
from flask import Blueprint, render_template
from flask_login import current_user

user_bp = Blueprint('user_bp', __name__)


@user_bp.route('/me')
@flask_login.login_required
def me():
    return render_template('profile.html',
                           user=current_user, include_header=True)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}{% endblock %}
    </title>

    {#bootstrap#}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO"
            crossorigin="anonymous"></script>
</head>
<body class="vh-100">

{% if include_header %}
    {% include 'components/header.html' %}
{% endif %}
<main class="vh-100">

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <ul class="flashes">
                {% for category, message in messages %}
                    <li class="alert alert-{{ category }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    <div id="flash-messages"></div>
    {% block content %}{% endblock %}
</main>
</body>
</html>

app/templates/book_creation_page.html
{% extends 'base.html' %}
{% block title %}Criar Livro{% endblock %}
{% block content %}
    <form>
        <div class="mb-3">
            <label for="title" class="form-label">título</label>
            <input type="text" class="form-control" id="title" name="title">
        </div>
        <div class="mb-3">
            <label for="genre" class="form-label">gênero</label>
            <input type="text" class="form-control" id="genre" name="genre">
        </div>
        <div class="mb-3">
            <label for="author" class="form-label">autor</label>
            <input type="text" class="form-control" id="author" name="author">
        </div>
        <div class="mb-3">
            <label for="publisher" class="form-label">editora</label>
            <input type="text" class="form-control" id="publisher" name="publisher">
        </div>
        <div class="mb-3">
            <label for="publication_date" class="form-label">data de publicação</label>
            <input type="date" class="form-control" id="pubDate" name="pubData">
        </div>
        <div class="mb-3">
            <label for="status" class="form-label">estado</label>
            <select name="status" id="status">
                <option value="new">novo</option>
                <option value="semi-new">semi-novo</option>
                <option value="used">usado</option>
            </select>
        </div>
        <div class="mb-3">
            <label for="donated" class="form-label">Doado</label>
            <input type="checkbox" class="form-check-input" id="donated" name="donate" value="True">
        </div>
        <div class="mb-3">
            <label for="unitPrice" class="form-label">Preço unitário</label>
            <input type="number" class="form-control" id="unitPrice" name="unitPrice">
        </div>
        <div class="mb-3">
            <label for="stock" class="form-label">Estoque</label>
            <input type="number" class="form-control" id="stock" name="stock">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

app/templates/catalog.html
{% extends 'base.html' %}
{% block title %}catálog{% endblock %}
{% block content %}
    {% if books %}
        {% for book in books %}
            <div class="card" style="width: 18rem;">
                <img src="..." class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ book.title }}</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                        card’s
                        content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>Sem livros no momento <a href="{{ url_for('book_bp.create_book') }}">adicionar</a> </p>
    {% endif %}
{% endblock %}

app/templates/components/header.html
<nav class="navbar navbar-expand-lg">
    <div class="container">
        <a class="navbar-brand" href="{{ url_for('home_bp.index') }}">Agora library</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                {% if not current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                           href="{{ url_for('auth_bp.login') }}">Login</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                           href="{{ url_for('auth_controller.logout') }}">
                            Logout
                        </a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user_bp.me') }}">Perfil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('book_bp.catalog') }}">Livros</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/templates/home.html
{% extends 'base.html' %}
{% block title %}home{% endblock %}
{% block content %}
    <div class="container">
        <h1>
            <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, amet commodi culpa deserunt
                distinctio
                dolorem eum exercitationem in itaque laborum, minima nobis officiis quae quidem, quis quo saepe
                voluptate
                voluptatum.
            </div>
            <div>Architecto assumenda beatae debitis eos est possimus qui. Animi ducimus inventore molestias pariatur
                qui
                quos, voluptatibus. Eius enim itaque libero nesciunt nulla praesentium reprehenderit temporibus veniam
                veritatis vitae! Adipisci, impedit?
            </div>
            <div>Adipisci at corporis cupiditate dolor dolore facilis id, illo illum impedit incidunt ipsum laborum
                minima
                modi nam nisi optio provident quaerat quo ratione repudiandae saepe tempora unde vel velit voluptatum!
            </div>
            <div>Ab eum illum, nostrum suscipit vel velit veniam? Ab aliquam, aliquid, assumenda corporis dicta
                distinctio
                dolorum eos esse eum, facere illo impedit nobis placeat rerum sed ullam ut! Eligendi, sunt.
            </div>
            <div>A, maxime odio quam quas soluta vitae voluptates. Ad alias consectetur corporis, dolor modi
                perspiciatis
                sed unde! Accusantium dolore, dolores esse eveniet, laudantium maiores minus, perferendis praesentium
                ratione soluta veniam?
            </div>
            <div>Amet aperiam autem commodi eius, eos error est fugit iure, minus molestiae nam nemo nesciunt nostrum
                perspiciatis praesentium quis sit vero vitae voluptatem voluptates. Accusamus consequatur earum
                praesentium
                reiciendis reprehenderit!
            </div>
            <div>Ad aliquam architecto atque corporis culpa dignissimos eius eligendi fugit harum id in iste maiores
                natus
                nemo nesciunt nostrum odio optio perspiciatis quas soluta tempora tempore temporibus ut, vel,
                voluptatum?
            </div>
            <div>Ad fugiat labore natus officiis. Adipisci deserunt eligendi molestias quas quos? Accusamus accusantium
                architecto assumenda deserunt distinctio, earum id labore mollitia natus nemo officiis porro quam qui
                quos,
                ratione tenetur.
            </div>
            <div>Accusantium architecto doloribus expedita explicabo in iusto nisi similique soluta temporibus
                veritatis.
                Ab, adipisci earum eos illo itaque maxime minus molestias neque nihil pariatur quae, quasi repellendus
                sed
                sint, veritatis.
            </div>
            <div>Aliquid aut blanditiis deserunt distinctio doloribus dolorum eaque excepturi hic iure laboriosam,
                molestias, nulla, obcaecati quisquam ratione saepe sint tempore unde. Beatae dolorem ipsam nisi, non
                numquam
                placeat voluptate voluptatum!
            </div>
            <div>Alias at debitis ducimus maiores nam quam sunt ullam! Accusamus ad architecto aspernatur dignissimos
                earum
                esse est exercitationem explicabo harum hic impedit iste officia officiis possimus praesentium, quis
                quos
                vitae.
            </div>
            <div>Accusantium natus officia repellendus tempora ut vero voluptatem voluptatum. Ab ad aperiam architecto
                atque
                blanditiis, consectetur consequatur cupiditate exercitationem maxime molestias nisi perferendis
                praesentium
                quae quasi quibusdam tenetur vero voluptatibus.
            </div>
            <div>Autem beatae eos iusto numquam obcaecati! Beatae, cumque dolorem est et ex illum incidunt laboriosam
                non
                nostrum, officiis quasi quo rem repellat sapiente suscipit? Dolorum iure nemo provident totam unde!
            </div>
            <div>Alias distinctio earum id inventore ipsa ipsum laboriosam nam, natus nihil non pariatur rem, repellat
                tenetur voluptas voluptatum. Ad at atque commodi dicta magni quam quisquam recusandae repudiandae sunt
                totam.
            </div>
            <div>Accusamus consectetur, culpa dolorem et explicabo ipsam labore laboriosam maxime modi natus nobis
                nostrum
                numquam officiis perferendis qui quibusdam quidem quos repellat repudiandae ullam vitae voluptas
                voluptatem.
                Doloribus, expedita officia!
            </div>
        </h1>
    </div>
{% endblock %}

app/templates/profile.html
{% extends 'base.html' %}
{% block title %}profile{% endblock %}
{% block content %}
    <form id="profileForm">
        <div class="mb-3">
            <label for="userName" class="form-label">Username</label>
            <input type="text" name="username" class="form-control"
                   id="userName" value="{{ current_user.username }}">
        </div>
        <div class="mb-3">
            <label for="userEmail" class="form-label">Email address</label>
            <input type="email" name="email" class="form-control"
                   id="userEmail" aria-describedby="emailHelp"
                   value="{{ current_user.email }}">
        </div>
        <div class="mb-3">
            <label for="userPassword" class="form-label">Password</label>
            <input type="password" name="password" class="form-control" id="userPassword"
                   value="{{ current_user.password }}">
        </div>
        <button type="submit" class="btn btn-primary" id="submitBtn" disabled>Submit</button>
    </form>
    <button type="button" class="btn btn-danger" id="deleteBtn">Deletar Conta</button>
    <script src="{{ url_for('static', filename='js/profile.js') }}" type="module"></script>
{% endblock %}